services:
  app:
    build:
      context: .
      target: production
    environment:
      - CHANNEL_ID=${CHANNEL_ID}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NAME=${NAME}
      - PERSONALITY=${PERSONALITY}
      - MIN_WAIT_TIME=${MIN_WAIT_TIME}
      - MAX_WAIT_TIME=${MAX_WAIT_TIME}
      - MAX_WAIT_MESSAGES=${MAX_WAIT_MESSAGES}
      - MAX_CONVERSATION_TIME=${MAX_CONVERSATION_TIME}
      - QUEUE_WAIT_TIME=${QUEUE_WAIT_TIME}
      - TYPING_WAIT_TIME=${TYPING_WAIT_TIME}
